require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BrainsController do

  # This should return the minimal set of attributes required to create a valid
  # Brain. As you add validations to Brain, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BrainsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all brains as @brains" do
      brain = Brain.create! valid_attributes
      get :index, {}, valid_session
      assigns(:brains).should eq([brain])
    end
  end

  describe "GET show" do
    it "assigns the requested brain as @brain" do
      brain = Brain.create! valid_attributes
      get :show, {:id => brain.to_param}, valid_session
      assigns(:brain).should eq(brain)
    end
  end

  describe "GET new" do
    it "assigns a new brain as @brain" do
      get :new, {}, valid_session
      assigns(:brain).should be_a_new(Brain)
    end
  end

  describe "GET edit" do
    it "assigns the requested brain as @brain" do
      brain = Brain.create! valid_attributes
      get :edit, {:id => brain.to_param}, valid_session
      assigns(:brain).should eq(brain)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Brain" do
        expect {
          post :create, {:brain => valid_attributes}, valid_session
        }.to change(Brain, :count).by(1)
      end

      it "assigns a newly created brain as @brain" do
        post :create, {:brain => valid_attributes}, valid_session
        assigns(:brain).should be_a(Brain)
        assigns(:brain).should be_persisted
      end

      it "redirects to the created brain" do
        post :create, {:brain => valid_attributes}, valid_session
        response.should redirect_to(Brain.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved brain as @brain" do
        # Trigger the behavior that occurs when invalid params are submitted
        Brain.any_instance.stub(:save).and_return(false)
        post :create, {:brain => { "name" => "invalid value" }}, valid_session
        assigns(:brain).should be_a_new(Brain)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Brain.any_instance.stub(:save).and_return(false)
        post :create, {:brain => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested brain" do
        brain = Brain.create! valid_attributes
        # Assuming there are no other brains in the database, this
        # specifies that the Brain created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Brain.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => brain.to_param, :brain => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested brain as @brain" do
        brain = Brain.create! valid_attributes
        put :update, {:id => brain.to_param, :brain => valid_attributes}, valid_session
        assigns(:brain).should eq(brain)
      end

      it "redirects to the brain" do
        brain = Brain.create! valid_attributes
        put :update, {:id => brain.to_param, :brain => valid_attributes}, valid_session
        response.should redirect_to(brain)
      end
    end

    describe "with invalid params" do
      it "assigns the brain as @brain" do
        brain = Brain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Brain.any_instance.stub(:save).and_return(false)
        put :update, {:id => brain.to_param, :brain => { "name" => "invalid value" }}, valid_session
        assigns(:brain).should eq(brain)
      end

      it "re-renders the 'edit' template" do
        brain = Brain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Brain.any_instance.stub(:save).and_return(false)
        put :update, {:id => brain.to_param, :brain => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested brain" do
      brain = Brain.create! valid_attributes
      expect {
        delete :destroy, {:id => brain.to_param}, valid_session
      }.to change(Brain, :count).by(-1)
    end

    it "redirects to the brains list" do
      brain = Brain.create! valid_attributes
      delete :destroy, {:id => brain.to_param}, valid_session
      response.should redirect_to(brains_url)
    end
  end

end
