require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PanesController do

  # This should return the minimal set of attributes required to create a valid
  # Pane. As you add validations to Pane, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PanesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all panes as @panes" do
      pane = Pane.create! valid_attributes
      get :index, {}, valid_session
      assigns(:panes).should eq([pane])
    end
  end

  describe "GET show" do
    it "assigns the requested pane as @pane" do
      pane = Pane.create! valid_attributes
      get :show, {:id => pane.to_param}, valid_session
      assigns(:pane).should eq(pane)
    end
  end

  describe "GET new" do
    it "assigns a new pane as @pane" do
      get :new, {}, valid_session
      assigns(:pane).should be_a_new(Pane)
    end
  end

  describe "GET edit" do
    it "assigns the requested pane as @pane" do
      pane = Pane.create! valid_attributes
      get :edit, {:id => pane.to_param}, valid_session
      assigns(:pane).should eq(pane)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pane" do
        expect {
          post :create, {:pane => valid_attributes}, valid_session
        }.to change(Pane, :count).by(1)
      end

      it "assigns a newly created pane as @pane" do
        post :create, {:pane => valid_attributes}, valid_session
        assigns(:pane).should be_a(Pane)
        assigns(:pane).should be_persisted
      end

      it "redirects to the created pane" do
        post :create, {:pane => valid_attributes}, valid_session
        response.should redirect_to(Pane.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pane as @pane" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pane.any_instance.stub(:save).and_return(false)
        post :create, {:pane => { "name" => "invalid value" }}, valid_session
        assigns(:pane).should be_a_new(Pane)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pane.any_instance.stub(:save).and_return(false)
        post :create, {:pane => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pane" do
        pane = Pane.create! valid_attributes
        # Assuming there are no other panes in the database, this
        # specifies that the Pane created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pane.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => pane.to_param, :pane => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested pane as @pane" do
        pane = Pane.create! valid_attributes
        put :update, {:id => pane.to_param, :pane => valid_attributes}, valid_session
        assigns(:pane).should eq(pane)
      end

      it "redirects to the pane" do
        pane = Pane.create! valid_attributes
        put :update, {:id => pane.to_param, :pane => valid_attributes}, valid_session
        response.should redirect_to(pane)
      end
    end

    describe "with invalid params" do
      it "assigns the pane as @pane" do
        pane = Pane.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pane.any_instance.stub(:save).and_return(false)
        put :update, {:id => pane.to_param, :pane => { "name" => "invalid value" }}, valid_session
        assigns(:pane).should eq(pane)
      end

      it "re-renders the 'edit' template" do
        pane = Pane.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pane.any_instance.stub(:save).and_return(false)
        put :update, {:id => pane.to_param, :pane => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pane" do
      pane = Pane.create! valid_attributes
      expect {
        delete :destroy, {:id => pane.to_param}, valid_session
      }.to change(Pane, :count).by(-1)
    end

    it "redirects to the panes list" do
      pane = Pane.create! valid_attributes
      delete :destroy, {:id => pane.to_param}, valid_session
      response.should redirect_to(panes_url)
    end
  end

end
